# Generated by Django 5.0.6 on 2024-07-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cartitem_game_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Finalizada', max_length=20),
        ),
    ]
