# Generated by Django 5.1.4 on 2024-12-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dcub4itgg/image/upload/v1733740981/tf9dia6ktszxmwxr2uiy.jpg', upload_to=''),
        ),
    ]
